Second day on Git
rubikvn2100/TestColabRepo pull request #2
Opened 2023-02-19 13:08 UTC by BrianNguyen420

Here is the update to mentor Khoa about how I practice on GIT.

2023-02-19 13:11 UTC, rubikvn2100 commented
Good Job on solving the first problem.

2023-02-20 02:17 UTC, rubikvn2100 requested changes

2023-02-20 02:17 UTC, rubikvn2100 commented on addition.test.py
> +class TestSumFuction(unittest.TestCase):
You should change "Sum" to "Addition".

2023-02-20 02:17 UTC, rubikvn2100 commented on multiply.test.py
> +class TestMulFuction(unittest.TestCase):
You should change "Mul" to "Multiply"

2023-02-20 02:21 UTC, BrianNguyen420 commented on addition.test.py
> +class TestSumFuction(unittest.TestCase):
I understand your request.

2023-02-20 02:22 UTC, BrianNguyen420 commented on multiply.test.py
> +class TestMulFuction(unittest.TestCase):
I acknowledge your request.

2023-02-20 03:35 UTC, rubikvn2100 commented
Great, keep going main.

2023-02-20 03:36 UTC, merged